// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG_UYLAyHtuefsSOFkvpQmL4ZoD5HULBw',
    appId: '1:383674534600:web:50d61b1ceb6ffa577933fd',
    messagingSenderId: '383674534600',
    projectId: 'fiona-fd9d1',
    authDomain: 'fiona-fd9d1.firebaseapp.com',
    storageBucket: 'fiona-fd9d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeuxFjrjoAOM2EI8Oz0GQtZ0_IycBFcR4',
    appId: '1:383674534600:android:e8304a9345f4fad47933fd',
    messagingSenderId: '383674534600',
    projectId: 'fiona-fd9d1',
    storageBucket: 'fiona-fd9d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNwDT2lZFGCx37Nf2_wuvg5Zl3tvAC9nA',
    appId: '1:383674534600:ios:185fc7befb7c3f0f7933fd',
    messagingSenderId: '383674534600',
    projectId: 'fiona-fd9d1',
    storageBucket: 'fiona-fd9d1.appspot.com',
    iosBundleId: 'com.example.fiona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNwDT2lZFGCx37Nf2_wuvg5Zl3tvAC9nA',
    appId: '1:383674534600:ios:aa09923c0921c65d7933fd',
    messagingSenderId: '383674534600',
    projectId: 'fiona-fd9d1',
    storageBucket: 'fiona-fd9d1.appspot.com',
    iosBundleId: 'com.example.fiona.RunnerTests',
  );
}
